#!/bin/sh

# Run tests (pest, static analysis, and rector dry-run)
echo "Running tests..."
composer test
if [ $? -ne 0 ]; then
    echo "Tests failed! Aborting commit."
    exit 1
fi

# Run PHPDocs generation
echo "Generating PHPDocs..."
composer php-docs
if [ $? -ne 0 ]; then
    echo "PHPDocs generation failed! Aborting commit."
    exit 1
fi

# Run Rector
echo "Running Rector..."
composer rector
if [ $? -ne 0 ]; then
    echo "Rector failed! Aborting commit."
    exit 1
fi

echo "Running Pint..."
composer pint
if [ $? -ne 0 ]; then
    echo "Pint failed! Aborting commit."
    exit 1
fi

echo "All checks passed! Proceeding with commit."